export const RELIGIONS = [
  'Hindu', 'Muslim', 'Sikh', 'Christian', 'Jain', 'Buddhist',
  'Zoroastrian', 'Jewish', 'Shinto', 'Taoist',
  "Baha'i", 'Confucianism', 'Druze', 'Yazidism', 'Rastafari', 'Tenrikyo',
  'Pagan', 'Unitarian Universalism', 'New Religious Movements',
  'Indigenous / Traditional', 'Samaritanism',
  'Atheist', 'Agnostic', 'Spiritual but not Religious', 'Secular / Humanist', 'No Religion',
  'Other',
]

export const CASTES = [
  "Ad Dharmi",
  "Adi Andhra",
  "Adi Dravida",
  "Adi Karnataka",
  "Agamudayar",
  "Agri",
  "Ahir",
  "Ahir - Ahir shimpi",
  "Ahirwar",
  "Ahom",
  "Ambalavasi",
  "Ambalavasi - Pisharody",
  "Ambalavasi - Poduval",
  "Amma Kodava",
  "Arakh Arakvanshiya",
  "Arekatica",
  "Arunthathiyar",
  "Arya Vysya",
  "Ayyaraka",
  "Badaga",
  "Badhai",
  "Bagdi",
  "Baghel Gaderiya",
  "Bahi",
  "Baidya",
  "Bairwa",
  "Baishnab",
  "Baishya",
  "Baishya - Saha",
  "Baishya Kapali",
  "Bajantri",
  "Balai",
  "Balija",
  "Balija - Balija Naidu",
  "Balija - Balija Reddy",
  "Balija - Ediga /Goud (Balija)",
  "Balija - Gajula / Kavarai",
  "Balija - Kapu",
  "Balija - Kavara",
  "Balija - Linga Balija",
  "Balija - Modikarlu",
  "Balija - Munnuru Kapu",
  "Balija - Musukama",
  "Balija - Namdarlu",
  "Balija - Pagadala",
  "Balija - Perika",
  "Balija - Setti Balija",
  "Balija - Surya Balija",
  "Balija - Telaga",
  "Balija - Thota",
  "Balija - Vada Balija",
  "Balija - Velama",
  "Balija - Waada Balija",
  "Balija Naidu",
  "Balija Naidu - Balija Naidu",
  "Balija Naidu - Balija Reddy",
  "Balija Naidu - Setti Balija",
  "Balija Naidu - Surya Balija",
  "Balija Naidu - Vada Balija",
  "Balija Naidu - Waada Balija",
  "Banayat Oriya",
  "Bania",
  "Bania - Agarwal",
  "Bania - Agrahari",
  "Bania - Asathi",
  "Bania - Ayodhyavasi",
  "Bania - Baniya Kumuti",
  "Bania - Barnwals",
  "Bania - Bisa Agarwal",
  "Bania - Chaturth",
  "Bania - Choudhary",
  "Bania - Dosar / Dusra",
  "Bania - Gahoi",
  "Bania - Gandha Vanika",
  "Bania - Gulahre",
  "Bania - Jaiswal",
  "Bania - Kalwar",
  "Bania - Kandu / Kanu",
  "Bania - Kanojia Kanu",
  "Bania - Kanyakubj Bania",
  "Bania - Kasaundhan",
  "Bania - Keshri / Kesarwani",
  "Bania - Khandelwal",
  "Bania - Komti Arya Vaishya",
  "Bania - Lad",
  "Bania - Madhesiya / Kawa / Halwai",
  "Bania - Mahajan",
  "Bania - Mahawar",
  "Bania - Maheshwari/Meshri",
  "Bania - Mahor",
  "Bania - Mahuri",
  "Bania - Marwari",
  "Bania - Modh Ghanchi",
  "Bania - Modi",
  "Bania - Nema",
  "Bania - Oswal",
  "Bania - Padmamavati Porwal",
  "Bania - Patwa",
  "Bania - Porwal / Porwar",
  "Bania - Rastogi",
  "Bania - Rathi",
  "Bania - Rauniyar",
  "Bania - Rauniyars",
  "Bania - Shaw / Sahu / Teli",
  "Bania - Sinduriya",
  "Bania - Sudi / Suri / Sundhi / Shaundik",
  "Bania - Ummaar / Umre / Bagaria",
  "Bania - Vaishnav",
  "Bania - Vani/Vaishya",
  "Bania - Varshneys",
  "Bania - Vijayvargia",
  "Banik",
  "Banjara",
  "Banjara - Lambani",
  "Barai",
  "Bari",
  "Baria",
  "Beldar",
  "Besta",
  "Bhajantr",
  "Bhatia",
  "Bhatraju",
  "Bhavsar",
  "Bhil",
  "Bhoi / Bhoi",
  "Bhoyar",
  "Bhulia / Meher",
  "Billava",
  "Bishnoi / Vishnoi",
  "Bondili",
  "Boyer",
  "Brahmakshatriya",
  "Brahmbatt",
  "Brahmin",
  "Brahmin - 6000 Niyogi",
  "Brahmin - Anavil",
  "Brahmin - Andhra",
  "Brahmin - Audichya",
  "Brahmin - Audichyasahashtra",
  "Brahmin - Bajkhedwal",
  "Brahmin - Bardai",
  "Brahmin - Barendra",
  "Brahmin - Bengali",
  "Brahmin - Bhargava",
  "Brahmin - Bhatt",
  "Brahmin - Bhumihar",
  "Brahmin - Brahacharanam",
  "Brahmin - BrahmBhatt",
  "Brahmin - Brajashtha Maithil",
  "Brahmin - Chittpavan Konkanastha",
  "Brahmin - Dadhich",
  "Brahmin - Daivadnya",
  "Brahmin - Danua",
  "Brahmin - Deshastha",
  "Brahmin - Devrukhe",
  "Brahmin - Dhiman",
  "Brahmin - Dravida",
  "Brahmin - Dunua",
  "Brahmin - Embrandiri",
  "Brahmin - Garhwali",
  "Brahmin - Gaud Saraswat (GSB)",
  "Brahmin - Gaur",
  "Brahmin - Gautam",
  "Brahmin - Goswami",
  "Brahmin - Gujar Gaur",
  "Brahmin - Gujrati",
  "Brahmin - Gurukkal",
  "Brahmin - Halua",
  "Brahmin - Havyaka",
  "Brahmin - Hoysala",
  "Brahmin - Iyengar",
  "Brahmin - Iyer",
  "Brahmin - Jangid",
  "Brahmin - Jangra",
  "Brahmin - Jhadua",
  "Brahmin - Jhijhotiya",
  "Brahmin - Jogi",
  "Brahmin - Jyotish",
  "Brahmin - Kannada",
  "Brahmin - Kanyakubj",
  "Brahmin - Karhade",
  "Brahmin - Karnataka",
  "Brahmin - Kashmiri Pandit",
  "Brahmin - Khadayat",
  "Brahmin - Khandelwal",
  "Brahmin - Khedaval",
  "Brahmin - Koknastha",
  "Brahmin - Kota",
  "Brahmin - Kulin",
  "Brahmin - Kumaoni",
  "Brahmin - Madhwa",
  "Brahmin - Maharashtra",
  "Brahmin - Maithil",
  "Brahmin - Malviya",
  "Brahmin - Marwari",
  "Brahmin - Mevada",
  "Brahmin - Modh",
  "Brahmin - Mohapatra Mahapatra",
  "Brahmin - Mohyal",
  "Brahmin - Nagar",
  "Brahmin - Nai / Nai",
  "Brahmin - Namboodiri",
  "Brahmin - Narmadiya",
  "Brahmin - Paliwal",
  "Brahmin - Panda",
  "Brahmin - Pandit",
  "Brahmin - Panicker",
  "Brahmin - Pareek",
  "Brahmin - Pushkarna",
  "Brahmin - Rajapuri Saraswat",
  "Brahmin - Rajasthani",
  "Brahmin - Rajgor",
  "Brahmin - Rarhi",
  "Brahmin - Rigvedi",
  "Brahmin - Rudraj",
  "Brahmin - Sachora",
  "Brahmin - Sakaldwipi",
  "Brahmin - Sanadya",
  "Brahmin - Sanchihar",
  "Brahmin - Sanketi",
  "Brahmin - Saraswat",
  "Brahmin - Sarotri",
  "Brahmin - Sarua",
  "Brahmin - Saryuparin",
  "Brahmin - Shivalili",
  "Brahmin - Shrimalli",
  "Brahmin - Sikhwal",
  "Brahmin - Smartha",
  "Brahmin - Sri Vaishnava",
  "Brahmin - Stanika",
  "Brahmin - Tapodhan",
  "Brahmin - Tyagi",
  "Brahmin - Utkal",
  "Brahmin - Vaidiki",
  "Brahmin - Vaikhanasa",
  "Brahmin - Vaikhawas",
  "Brahmin - Vaishnav",
  "Brahmin - Valam",
  "Brahmin - Velanadu",
  "Brahmin - Viswa",
  "Brahmin - Vyas",
  "Brahmin - Yajurvedi",
  "Brahmin - Zalora",
  "Brahmo",
  "Buddhar",
  "Bunt Shetty",
  "Chalawadi / Holeya",
  "Chamar",
  "Chambhar",
  "Chandravanshi Kahar",
  "Charan",
  "Chasa",
  "Chattada Sri Vaishnava",
  "Chaudary",
  "Chaudary - Ghrit",
  "Chaurasia",
  "Chennadasar",
  "Cheramar",
  "Chettiar",
  "Chettiar - 24 Manai Telugu Chettiar",
  "Chettiar - 24 Manai Telugu Chettiar 16 Veedu",
  "Chettiar - 24 Manai Telugu Chettiar 8 Veedu",
  "Chettiar - Achirapakkam Chettiar",
  "Chettiar - Agaram Vellan Chettiar",
  "Chettiar - Arya Vysya",
  "Chettiar - Ayira Vysya",
  "Chettiar - Beri Chettiar",
  "Chettiar - Devanga Chettiar",
  "Chettiar - Elur Chetty",
  "Chettiar - Gandla / Ganiga",
  "Chettiar - Kasukara",
  "Chettiar - Kongu Chettiar",
  "Chettiar - Kuruhini Chetty",
  "Chettiar - Manjapudur Chettiar",
  "Chettiar - Nattukottai Chettiar",
  "Chettiar - Padma Saliar",
  "Chettiar - Pannirandam Chettiar",
  "Chettiar - Parvatha Rajakulam",
  "Chettiar - Pattinavar",
  "Chettiar - Pattusali",
  "Chettiar - Sadhu Chetty",
  "Chettiar - Saiva Vellan Chettiar",
  "Chettiar - Senai Thalaivar",
  "Chettiar - Sozhia Chettiar",
  "Chettiar - Telugupatti",
  "Chettiar - Vadambar",
  "Chettiar - Vaniya Chettiar",
  "Chettiar - Vellan Chettiar",
  "Chhetri",
  "Chhippolu Mera",
  "CKP",
  "Coorgi",
  "Coorgi - Kodava",
  "Dasapalanjika Kannada Saineegar",
  "Devadigas",
  "Devang Koshti",
  "Devang Koshti - Devanga",
  "Devang Koshti - Devanga Chettiar",
  "Devanga",
  "Devendra Kula Vellalar",
  "Devipujak (Vaghri)",
  "Dewar / Dhibara",
  "Dhanak",
  "Dhangar",
  "Dhanuk",
  "Dheevara",
  "Dhiman",
  "Dhoba",
  "Dhobi",
  "Dhobi - Kanaujia",
  "Dhor / Dhoar",
  "Dommala",
  "Dumal",
  "Dusadh",
  "Edigas",
  "Ezhava",
  "Ezhava - Ezhava Panicker",
  "Ezhava - Ezhava Thandan",
  "Ezhava - Kavuthiya",
  "Ezhava - Thiyya",
  "Ezhuthachan",
  "Gabit",
  "Ganda",
  "Gangai / Ganesh",
  "Ganiga",
  "Ganiga - Shiva Jyothipana",
  "Garhwali",
  "Gatti",
  "Gavali",
  "Gavandi",
  "Gavara",
  "Ghasi",
  "Ghisadi",
  "Ghumar",
  "Goala",
  "Goan",
  "Gond Gondi Raj Gond",
  "Gondhali",
  "Gopal",
  "Goud",
  "Gounder",
  "Gounder - Kongu Vellala Gounder",
  "Gowda - Musuku",
  "Gowda - Namadari",
  "Gowda - Okkaliga",
  "Gowda - Reddy",
  "Gowda - Sarpa",
  "Gowda - Uttamakula",
  "Gramani",
  "Gudia",
  "Gujjar",
  "Gujjar - Dode",
  "Gujjar - Leva",
  "Guptan",
  "Gurav",
  "Halba Koshti",
  "Hegde",
  "Helava",
  "Holar",
  "Jaalari",
  "Jaiswal",
  "Jandra",
  "Jangam",
  "Jat",
  "Jat - Agharia",
  "Jat - Agoh",
  "Jat - Agra",
  "Jat - Ahlawat",
  "Jat - Alwal",
  "Jat - Antil / Antal",
  "Jat - Arya",
  "Jat - Badhwar",
  "Jat - Bagaria",
  "Jat - Bagri",
  "Jat - Bains",
  "Jat - Balhara",
  "Jat - Balyan",
  "Jat - Bana",
  "Jat - Barach",
  "Jat - Bargoti",
  "Jat - Beniwal",
  "Jat - Bhal",
  "Jat - Bhambu",
  "Jat - Bhodu",
  "Jat - Bomal",
  "Jat - Budania",
  "Jat - Bugaliya",
  "Jat - Chahal",
  "Jat - Chaudhry",
  "Jat - Chauhan",
  "Jat - Chhikara / Chikara",
  "Jat - Chillar",
  "Jat - Dabhas",
  "Jat - Dagar",
  "Jat - Daguwa",
  "Jat - Dahiya",
  "Jat - Dalal",
  "Jat - Dangi",
  "Jat - Dara",
  "Jat - Deshwal",
  "Jat - Dhaka",
  "Jat - Dhama",
  "Jat - Dhanchak",
  "Jat - Dhanda",
  "Jat - Dhankhar",
  "Jat - Dhillon",
  "Jat - Dhomi",
  "Jat - Dhoot",
  "Jat - Dhoriwal",
  "Jat - Dhull",
  "Jat - Dollya",
  "Jat - Dudi",
  "Jat - Duhan",
  "Jat - Gahlot",
  "Jat - Garhwal",
  "Jat - Gehlawat",
  "Jat - Ghangas",
  "Jat - Gill",
  "Jat - Godara",
  "Jat - Grewal",
  "Jat - Guila",
  "Jat - Heer",
  "Jat - Hooda",
  "Jat - Jaglon",
  "Jat - Jakhar",
  "Jat - Jam",
  "Jat - Jaswal",
  "Jat - Jatasara",
  "Jat - Jewlia",
  "Jat - Jutrana",
  "Jat - Kadian",
  "Jat - Kahlon",
  "Jat - Kajala",
  "Jat - Kakran",
  "Jat - Kalen",
  "Jat - Kaliramna",
  "Jat - Kalkhanse",
  "Jat - Karwasra",
  "Jat - Kaswan",
  "Jat - Kataria",
  "Jat - Khakar",
  "Jat - Khallia",
  "Jat - Kharb",
  "Jat - Khatkar",
  "Jat - Khatri",
  "Jat - Kherwa",
  "Jat - Khichad",
  "Jat - Kothari",
  "Jat - Kuhar",
  "Jat - Kulhari",
  "Jat - Kundu",
  "Jat - Lakhlhan",
  "Jat - Lakra",
  "Jat - Lamba",
  "Jat - Lamoria",
  "Jat - Lather",
  "Jat - Lathwal",
  "Jat - Latyan",
  "Jat - Laur",
  "Jat - Lehga",
  "Jat - Maan",
  "Jat - Mahan",
  "Jat - Malhan",
  "Jat - Malik",
  "Jat - Mandhan",
  "Jat - Mangat",
  "Jat - Mann Rai",
  "Jat - Meel",
  "Jat - Mehria",
  "Jat - Mhla",
  "Jat - Mohar",
  "Jat - Moond",
  "Jat - Mor / More",
  "Jat - Nain",
  "Jat - Nairwal",
  "Jat - Nandal",
  "Jat - Nara",
  "Jat - Natt / Nat",
  "Jat - Nauhr",
  "Jat - Nehra",
  "Jat - Nitharwal",
  "Jat - Ola",
  "Jat - Pachehra",
  "Jat - Palsania",
  "Jat - Panghal",
  "Jat - Panwar",
  "Jat - Parihar",
  "Jat - Pattor",
  "Jat - Pawar",
  "Jat - Phalaswal",
  "Jat - Phogat",
  "Jat - Pilania",
  "Jat - Pooni",
  "Jat - Punia",
  "Jat - Rahan",
  "Jat - Rajaura",
  "Jat - Rana",
  "Jat - Rangi",
  "Jat - Ranwa",
  "Jat - Rao",
  "Jat - Rathi",
  "Jat - Rawal",
  "Jat - Redhu",
  "Jat - Repswal",
  "Jat - Saharan",
  "Jat - Sandhi",
  "Jat - Sangawan",
  "Jat - Sansanwal",
  "Jat - Saran",
  "Jat - Saroha",
  "Jat - Sarot",
  "Jat - Sehrawat",
  "Jat - Sheoran",
  "Jat - Shokeen",
  "Jat - Sidhu",
  "Jat - Sikarwar",
  "Jat - Sindhu",
  "Jat - Singhal",
  "Jat - Sinsinwar",
  "Jat - Sirohi",
  "Jat - Siwach",
  "Jat - Solanki",
  "Jat - Suhag",
  "Jat - Sunda",
  "Jat - Takhar",
  "Jat - Tanar",
  "Jat - Tanwar",
  "Jat - Tevatia",
  "Jat - Thakaran",
  "Jat - Thenua",
  "Jat - Thori",
  "Jat - Tokas",
  "Jat - Tomar",
  "Jatav",
  "Jetty Malla",
  "Jingar",
  "Julaha",
  "Kachara",
  "Kahar",
  "Kaibarta",
  "Kaikaala",
  "Kakkalan",
  "Kalal",
  "Kalanji",
  "Kalar",
  "Kalinga",
  "Kalinga Vysya",
  "Kalita",
  "Kalwar",
  "Kamboj",
  "Kamma",
  "Kammala",
  "Kanakkaan Padonna",
  "Kanakkkan Padanna",
  "Kandara",
  "Kaniyan",
  "Kansari",
  "Kansyakaar",
  "Kapol",
  "Kapu",
  "Kapu - Baliya/Balija Naidu",
  "Kapu - Ediga /Goud (Balija)",
  "Kapu - Gajula / Kavarai",
  "Kapu - Kapu All",
  "Kapu - Kapu Munnuru",
  "Kapu - Kapu Naidu",
  "Kapu - kurupu / Kapu",
  "Kapu - Ontari",
  "Kapu - Perika",
  "Kapu - Reddy",
  "Kapu - Setty Balija",
  "Kapu - Surya Balija",
  "Kapu - Telaga",
  "Kapu - Turupu Kapu",
  "Kapu - Velama",
  "Kapu Munnuru",
  "Karakala Bhakthula",
  "Karana",
  "Karmakar",
  "Karuneegar",
  "Kasar",
  "Kashyap",
  "Kashyap - Nishad",
  "Katiya",
  "Kayastha",
  "Kayastha - Ambashtha",
  "Kayastha - Ambashtha Kayastha",
  "Kayastha - Asthana",
  "Kayastha - Barujibi",
  "Kayastha - Basu",
  "Kayastha - Bengali Kayastha",
  "Kayastha - Bhatnagar",
  "Kayastha - Bose",
  "Kayastha - Chanda",
  "Kayastha - Dass",
  "Kayastha - Dey",
  "Kayastha - Dhar",
  "Kayastha - Dutta",
  "Kayastha - Ghosh",
  "Kayastha - Gour",
  "Kayastha - Guha",
  "Kayastha - Johri",
  "Kayastha - Karna",
  "Kayastha - Kars",
  "Kayastha - Kulin",
  "Kayastha - Kulshreshtha",
  "Kayastha - Mathur",
  "Kayastha - Mitra",
  "Kayastha - Nag",
  "Kayastha - Nandi",
  "Kayastha - Nigam",
  "Kayastha - Palit",
  "Kayastha - Paul",
  "Kayastha - Rakshit",
  "Kayastha - Rarhi",
  "Kayastha - Roy",
  "Kayastha - Saxena",
  "Kayastha - Sen",
  "Kayastha - Sil",
  "Kayastha - Sinha",
  "Kayastha - Srivastava",
  "Khandayat",
  "Khandayat - Kalinja",
  "Kharvi",
  "Kharwar",
  "Khatik",
  "Khatri",
  "Khatri - Anand",
  "Khatri - Arora",
  "Khatri - Bagga",
  "Khatri - Bahl",
  "Khatri - Batra",
  "Khatri - Bedi",
  "Khatri - Behal",
  "Khatri - Behl",
  "Khatri - Beri",
  "Khatri - Bhalla",
  "Khatri - Bhandari",
  "Khatri - Bhasin",
  "Khatri - Bhatti",
  "Khatri - Chaddha",
  "Khatri - Chadha",
  "Khatri - Chandok",
  "Khatri - Chaudhary",
  "Khatri - Chhabra",
  "Khatri - Chopra",
  "Khatri - Choudhuri",
  "Khatri - Dang",
  "Khatri - Dhawan",
  "Khatri - Dhir",
  "Khatri - Duggal",
  "Khatri - Ghai",
  "Khatri - Handa",
  "Khatri - Jaggi",
  "Khatri - Jairath",
  "Khatri - Jerath",
  "Khatri - Jham",
  "Khatri - Kakkar",
  "Khatri - Kapur / Kapoor",
  "Khatri - Kehar",
  "Khatri - Khanna",
  "Khatri - Khosla",
  "Khatri - Khukrain",
  "Khatri - Khullar",
  "Khatri - Kochhar",
  "Khatri - Kohli",
  "Khatri - Lamba",
  "Khatri - Mahendru",
  "Khatri - Malhotra",
  "Khatri - Marwah",
  "Khatri - Mehra",
  "Khatri - Mehrotra",
  "Khatri - Nanda",
  "Khatri - Nayyar",
  "Khatri - Oberoi",
  "Khatri - Ohri",
  "Khatri - Passi",
  "Khatri - Puri",
  "Khatri - Sabharwal",
  "Khatri - Sahni",
  "Khatri - Sareen",
  "Khatri - Sarin",
  "Khatri - Sawhney",
  "Khatri - Sehgal",
  "Khatri - Sekhri",
  "Khatri - Seth",
  "Khatri - Sethi",
  "Khatri - Sobti",
  "Khatri - Sodhi",
  "Khatri - Sondhi",
  "Khatri - Soni",
  "Khatri - Sood",
  "Khatri - Suri",
  "Khatri - Talwar",
  "Khatri - Tandon",
  "Khatri - Thapar",
  "Khatri - Tuli",
  "Khatri - Uppal",
  "Khatri - Vadhera",
  "Khatri - Verma",
  "Khatri - Vij",
  "Khatri - Vohra",
  "Khatri - Wadhawan",
  "Khatri - Wahi",
  "Khatri - Walia",
  "Koeri / Koiri",
  "Koli",
  "Koli - Mahadev",
  "Koli - Mangela",
  "Koli - Mangela Gounder - Aadai",
  "Koli - Mangela Gounder - Aadhhi",
  "Koli - Mangela Gounder - Aadhi",
  "Koli - Mangela Gounder - Aanthai",
  "Koli - Mangela Gounder - Aavan",
  "Koli - Mangela Gounder - Alagan",
  "Koli - Mangela Gounder - Andai",
  "Koli - Mangela Gounder - Andhuvan",
  "Koli - Mangela Gounder - Cheran",
  "Koli - Mangela Gounder - Devendran",
  "Koli - Mangela Gounder - Eenjan",
  "Koli - Mangela Gounder - Ennai",
  "Koli - Mangela Gounder - Kaadai",
  "Koli - Mangela Gounder - Kaari",
  "Koli - Mangela Gounder - Kanakkan",
  "Koli - Mangela Gounder - Kannan",
  "Koli - Mangela Gounder - Kannandhai",
  "Koli - Mangela Gounder - Keeran",
  "Koli - Mangela Gounder - Koorai",
  "Koli - Mangela Gounder - Koventhar",
  "Koli - Mangela Gounder - Kuzhlaayan",
  "Koli - Mangela Gounder - Maadai",
  "Koli - Mangela Gounder - Maniyan",
  "Koli - Mangela Gounder - Medhi",
  "Koli - Mangela Gounder - Muthan",
  "Koli - Mangela Gounder - Muzhlukkadhan",
  "Koli - Mangela Gounder - Natthu Gounder",
  "Koli - Mangela Gounder - Odhaalalar",
  "Koli - Mangela Gounder - Paandian",
  "Koli - Mangela Gounder - Padaithalaiyan",
  "Koli - Mangela Gounder - Panaiyan",
  "Koli - Mangela Gounder - Panangadai",
  "Koli - Mangela Gounder - Pannai",
  "Koli - Mangela Gounder - Pannan",
  "Koli - Mangela Gounder - Pavalan",
  "Koli - Mangela Gounder - Payiran",
  "Koli - Mangela Gounder - Periyan",
  "Koli - Mangela Gounder - Perizhanthan",
  "Koli - Mangela Gounder - Perunkudi",
  "Koli - Mangela Gounder - Pillan",
  "Koli - Mangela Gounder - Podiyan",
  "Koli - Mangela Gounder - Ponnan",
  "Koli - Mangela Gounder - Poochadhai Poodhiyan",
  "Koli - Mangela Gounder - Poosan",
  "Koli - Mangela Gounder - Sathandhai",
  "Koli - Mangela Gounder - Sedan",
  "Koli - Mangela Gounder - Sellan",
  "Koli - Mangela Gounder - Sempoothan",
  "Koli - Mangela Gounder - Sengannan",
  "Koli - Mangela Gounder - Sengunni",
  "Koli - Mangela Gounder - Seralan",
  "Koli - Mangela Gounder - Sevadi",
  "Koli - Mangela Gounder - Thodai",
  "Koli - Mangela Gounder - Thooran",
  "Koli - Mangela Gounder - Vannakkan",
  "Koli - Mangela Gounder - Veliyan",
  "Koli - Mangela Gounder - Vellamban",
  "Koli - Mangela Gounder - Venduvan",
  "Koli - Mangela Gounder - Vili",
  "Koli - Mangela Gounder - Viliyan",
  "Konkani",
  "Koracha",
  "Korama",
  "Kori",
  "Kori / Koli",
  "Korvi",
  "Koshti",
  "Krishnavaka",
  "Kshatriya",
  "Kshatriya - Agnikula Kshatriya",
  "Kshatriya - Aguri Ugra Kshatriya",
  "Kshatriya - Amethia",
  "Kshatriya - Bachhil",
  "Kshatriya - Bagel",
  "Kshatriya - Baghela / Veghela",
  "Kshatriya - Banafar",
  "Kshatriya - Bhadoria",
  "Kshatriya - Bhandari",
  "Kshatriya - Bhardwaj",
  "Kshatriya - Bhatraju",
  "Kshatriya - Bhavasar Kshatriya",
  "Kshatriya - Bundela",
  "Kshatriya - Chopra",
  "Kshatriya - Chudasa",
  "Kshatriya - Dangi",
  "Kshatriya - Dhawan",
  "Kshatriya - Dixit",
  "Kshatriya - Gaherwar",
  "Kshatriya - Gargvansi",
  "Kshatriya - Gaur",
  "Kshatriya - Hada",
  "Kshatriya - Haihaivanshi",
  "Kshatriya - Jaiswar",
  "Kshatriya - Janwar",
  "Kshatriya - Kandera",
  "Kshatriya - Kapur",
  "Kshatriya - Katiyar",
  "Kshatriya - Khandayat",
  "Kshatriya - Khanna",
  "Kshatriya - Khare",
  "Kshatriya - Kshatriya Raju",
  "Kshatriya - Kshatriya Raju Chandravamsam",
  "Kshatriya - Kshatriya Raju Suryavamsam",
  "Kshatriya - Kumawat",
  "Kshatriya - Kurmi",
  "Kshatriya - Mehra",
  "Kshatriya - Nagvanshi",
  "Kshatriya - Negi",
  "Kshatriya - Niari",
  "Kshatriya - Nikhumbh",
  "Kshatriya - Paliwal",
  "Kshatriya - Pawar",
  "Kshatriya - Perika Puragiri Kshatriya",
  "Kshatriya - Pundir",
  "Kshatriya - Raikwar",
  "Kshatriya - Rajkumar",
  "Kshatriya - Rajwar",
  "Kshatriya - Rama Kshatriya",
  "Kshatriya - Rathor",
  "Kshatriya - Rawal",
  "Kshatriya - Rawat",
  "Kshatriya - Sahni",
  "Kshatriya - Saithwar - Mall",
  "Kshatriya - Sami",
  "Kshatriya - Sengar",
  "Kshatriya - Seth",
  "Kshatriya - Shrinet",
  "Kshatriya - Singh",
  "Kshatriya - Sisodiya",
  "Kshatriya - Soma Vamsha Arya Kshatriya",
  "Kshatriya - Somavanshi Sahasrarjun Kshatriya",
  "Kshatriya - Somvanshi",
  "Kshatriya - Tandon",
  "Kshatriya - Tanwar",
  "Kshatriya - Thogata Veera Kshatriya",
  "Kshatriya - Tomar / Tanwar",
  "Kshatriya - Tong Kshatriya",
  "Kshatriya - Vahi",
  "Kshatriya - Vohra",
  "Kshatriya - Wadhwa",
  "Kudumbi",
  "Kulalar",
  "Kulita",
  "Kurava",
  "Kuravan / Kuravar",
  "Kurmi",
  "Kurmi - Awadiya",
  "Kurmi - Baghel",
  "Kurmi - Chandel",
  "Kurmi - Chandra",
  "Kurmi - Chandrakar",
  "Kurmi - Chandrawanshi",
  "Kurmi - Chaudhari",
  "Kurmi - Chaudhary",
  "Kurmi - Deshmukh",
  "Kurmi - Gangwar",
  "Kurmi - Ghamaila",
  "Kurmi - Jaiswar",
  "Kurmi - Kashyap",
  "Kurmi - Katiyar",
  "Kurmi - Kochyasa",
  "Kurmi - Kumar",
  "Kurmi - Kushwaha (Koiri)",
  "Kurmi - Mahata",
  "Kurmi - Mahato",
  "Kurmi - Mahto",
  "Kurmi - Parganiha",
  "Kurmi - Patel",
  "Kurmi - Patidar",
  "Kurmi - Prasad",
  "Kurmi - Rai",
  "Kurmi - Sachan",
  "Kurmi - Singh",
  "Kurmi - Verma",
  "Kuruba",
  "Kuruhina Shetty",
  "Kurumbar",
  "Kushwaha",
  "Kutchhi",
  "Kutchhi Gurjar",
  "Lambadi",
  "Laxminarayan Gola",
  "Leva Patidar",
  "Leva Patil",
  "Lingayat",
  "Lingayat - Agasa",
  "Lingayat - Akkasali",
  "Lingayat - Aradhya",
  "Lingayat - Balegala",
  "Lingayat - Banagar",
  "Lingayat - Banajiga",
  "Lingayat - Bhandari",
  "Lingayat - Bilijedaru",
  "Lingayat - Bilimagga",
  "Lingayat - Chaturtha",
  "Lingayat - Dikshwant",
  "Lingayat - Ganiga",
  "Lingayat - Gowda",
  "Lingayat - Gowli",
  "Lingayat - Gurav",
  "Lingayat - Hadapada",
  "Lingayat - Hatgar",
  "Lingayat - Hoogar / Huger / Jeer",
  "Lingayat - Jadar",
  "Lingayat - Jangam",
  "Lingayat - Kudu Vokkaliga",
  "Lingayat - Kumbhar",
  "Lingayat - Kumbhar / Kumbhara",
  "Lingayat - Kuruhina Setty",
  "Lingayat - Lamba",
  "Lingayat - Lolagonda",
  "Lingayat - Madivala",
  "Lingayat - Malgar",
  "Lingayat - Mali",
  "Lingayat - Neelagar",
  "Lingayat - Neeli / Neelagar",
  "Lingayat - Neygi",
  "Lingayat - Nolamba",
  "Lingayat - Pancham",
  "Lingayat - Panchamasali",
  "Lingayat - Pattasali",
  "Lingayat - Reddy Reddi",
  "Lingayat - Sadar",
  "Lingayat - Sajjan / Sajjanagar",
  "Lingayat - Setty",
  "Lingayat - Shilwant",
  "Lingayat - Shiva Simpi",
  "Lingayat - Vani",
  "Lingayat - Veerashaiva",
  "Lohan",
  "Lohana",
  "Lohana - Ghoghari",
  "Lohana - Halai",
  "Lohana - Kutchhi",
  "Lohana - Vaishnav",
  "Lohar",
  "Lubana",
  "Madiga",
  "Mahar",
  "Mahendra",
  "Maheshwari",
  "Mahindra",
  "Mahisya",
  "Majabi Mazhbi",
  "Mala",
  "Mali",
  "Mallah",
  "Mallah - Kewat / Keot",
  "Mallah - Nishad",
  "Manikpuri",
  "Manipuri",
  "Manjhi",
  "Mannan / Velon / Vannan",
  "Mapila",
  "Maratha",
  "Maratha - 96 Kuli Maratha",
  "Maratha - 96K Kokanastha",
  "Maratha - Aramari Gabit",
  "Maratha - Deshastha Maratha",
  "Maratha - Deshmukh",
  "Maratha - Deshtha Maratha",
  "Maratha - Gomantak Maratha",
  "Maratha - Jhadav",
  "Maratha - Kokanastha Maratha",
  "Maratha - Kunbi Dhanoje",
  "Maratha - Kunbi Khaire",
  "Maratha - Kunbi Khedule",
  "Maratha - Kunbi Lonari",
  "Maratha - Kunbi Maratha",
  "Maratha - Kunbi Tirale",
  "Maratha - Malwani",
  "Maratha - Maratha Kshatriya",
  "Maratha - Parit",
  "Maratha - Patil",
  "Maratha - Sonar",
  "Maratha - Suthar",
  "Meru",
  "Meru Darji",
  "Mochi",
  "Modak",
  "Mogaveera",
  "Monchi",
  "Motati Reddy",
  "Mudalair / Mudaliar",
  "Mudaliar - Agamudayar / Arcot / Thuluva Vellala",
  "Mudaliar - Isai Vellalar",
  "Mudaliar - Kerala Mudali",
  "Mudaliar - Kongu Vellala Gounder",
  "Mudaliar - Mudaliar All",
  "Mudaliar - Mudaliar Arcot",
  "Mudaliar - Mudaliar Saiva",
  "Mudaliar - Mudaliar Saiva Pillai Tirunelveli",
  "Mudaliar - Mudaliar Sengupta",
  "Mudaliar - Saiva Pillai Tirunelveli",
  "Mudaliar - Sengunthar / Kaikolar",
  "Mudaliar - Sozhiya Vellalar",
  "Mudaliar - Thondai Mandala Vellala",
  "Mudaliar - Veerakodi Vellala",
  "Mudiraj",
  "Muthuraja",
  "Naagavamsamsam",
  "Nadar",
  "Nadar - Kongu Nadar",
  "Nagaralu",
  "Naicker",
  "Naicker - Naicker others",
  "Naicker - Naicker-Vanniya Kula Kshatriyar",
  "Naicker - Rajaka Chakali Dhobi",
  "Naidu",
  "Naidu - Baliya / Balija Naidu",
  "Naidu - Ediga / Goud",
  "Naidu - Gajula Kavarai",
  "Naidu - Gavara",
  "Naidu - Kamma",
  "Naidu - Kapu Naidu",
  "Naidu - Munnuru Kapu",
  "Naidu - Mutharaja",
  "Naidu - Perika",
  "Naidu - Raja Kambalathu Naicker",
  "Naidu - Raju",
  "Naidu - Reddy",
  "Naidu - Shetty Balija",
  "Naidu - Surya Balija",
  "Naidu - Telaga",
  "Naidu - Turupu Kapu",
  "Naidu - Vada Balija",
  "Naidu - Vadugan",
  "Naidu - Velama",
  "Naidu - Yadava Naidu",
  "Naik Nayak Nayaka",
  "Nair",
  "Nair - Adiyodi",
  "Nair - Anthoor",
  "Nair - Chekkala Nair",
  "Nair - Illam",
  "Nair - Kaimal",
  "Nair - Kartha",
  "Nair - Kiryathil",
  "Nair - Kurup",
  "Nair - Maniyani",
  "Nair - Mannadiar",
  "Nair - Marar",
  "Nair - Menon",
  "Nair - Nair All",
  "Nair - Nair-Vaniya",
  "Nair - Nambiar",
  "Nair - Panicker",
  "Nair - Pillai",
  "Nair - Poduval",
  "Nair - Thampi",
  "Nair - Tharakan",
  "Nair - Unnithan",
  "Nair - Vellala Pillai",
  "Nair - Veluthedathu",
  "Nair - Vilakkithala",
  "Namasudra / Namosudra",
  "Nambiar",
  "Nambisan",
  "Namboodiri",
  "Namdev Chhipa",
  "Nandi wale",
  "Napit",
  "Nath Jogi",
  "Nayee (Barber)",
  "Nepali",
  "Nessi / Kurni",
  "Nhavi",
  "Nonia",
  "OBC",
  "Odan",
  "Oraon",
  "Oswal",
  "Otari",
  "Padmashali",
  "Padmashali - Devanga",
  "Padmashali - Jaandra",
  "Padmashali - Kaikaala",
  "Padmashali - Karakala Bhakthula",
  "Padmashali - Karni Bhakthula",
  "Padmashali - Kurni",
  "Padmashali - Neeli Saali",
  "Padmashali - Nessi",
  "Padmashali - Pattusali",
  "Padmashali - Shettigar",
  "Padmashali - Swakula Saali",
  "Padmashali - Thogata Veerakshathriya",
  "Pal",
  "Panan",
  "Panchal",
  "Panchamsali",
  "Pandaram",
  "Panicker",
  "Pano",
  "Paravan Bhartar",
  "Parkava Kulam",
  "Parvatha Rajakulam",
  "Pasi",
  "Paswan / Dusadh",
  "Patel",
  "Patel - Anjana (Chowdary) Patel",
  "Patel - Desai",
  "Patel - Dodia",
  "Patel - Kadava Patel",
  "Patel - Leva - 27 Gam",
  "Patel - Leva - Baavis Gam",
  "Patel - Leva - Chaa Gam",
  "Patel - Leva - Chovis Gam",
  "Patel - Leva - Mota Sattavi",
  "Patel - Leva - Nani Sattavi",
  "Patel - Leva - Panch Gam",
  "Patel - Leva Patel",
  "Patel Lodhi",
  "Pathare Prabhu",
  "Patnaick",
  "Prajapati",
  "Pulaya Chruman",
  "Rabari",
  "Raigar",
  "Raikwar",
  "Rajaka",
  "Rajaka - Rajaka Vannar",
  "Rajbhar",
  "Rajbongshi",
  "Rajpurohit",
  "Rajput",
  "Rajput - Aheria Rajput",
  "Rajput - Baghel",
  "Rajput - Bais",
  "Rajput - Bankawat",
  "Rajput - Bargujar",
  "Rajput - Bhadauria",
  "Rajput - Bharbhunja",
  "Rajput - Bhatti",
  "Rajput - Bhriguvansha",
  "Rajput - Bisen",
  "Rajput - Bisht",
  "Rajput - Chandel",
  "Rajput - Chandravanshi",
  "Rajput - Chandrawat",
  "Rajput - Chauhan",
  "Rajput - Chawda / Chavada",
  "Rajput - Chib",
  "Rajput - Chundawat",
  "Rajput - Dhakare",
  "Rajput - Dixit",
  "Rajput - Doaad",
  "Rajput - Dogra",
  "Rajput - Durgavanshi",
  "Rajput - Gahlot",
  "Rajput - Garhwal",
  "Rajput - Gautam",
  "Rajput - Gogawat",
  "Rajput - Gohil",
  "Rajput - Goud / Gaur",
  "Rajput - Jadeja",
  "Rajput - Jadon",
  "Rajput - Jamwal",
  "Rajput - Janjua",
  "Rajput - Jasrotia",
  "Rajput - Jaswal",
  "Rajput - Jhala",
  "Rajput - Kachwaha",
  "Rajput - Kalyat",
  "Rajput - Katoch",
  "Rajput - Kaushik",
  "Rajput - Khadagvanshi Khagi",
  "Rajput - Khangarot",
  "Rajput - Khati",
  "Rajput - Kirar",
  "Rajput - Kumaoni",
  "Rajput - Kuruvanshi",
  "Rajput - Kushwaha",
  "Rajput - Lodhi Rajput",
  "Rajput - Lonia Lonia Lunia",
  "Rajput - Madad",
  "Rajput - Mahror",
  "Rajput - Mahthan",
  "Rajput - Mahyavanshi",
  "Rajput - Manhas",
  "Rajput - Nagvanshi",
  "Rajput - Naruka",
  "Rajput - Nathawat",
  "Rajput - Negi",
  "Rajput - Nikumbh",
  "Rajput - Oad Rajput",
  "Rajput - Parihar",
  "Rajput - Parmar",
  "Rajput - Pratihar",
  "Rajput - Pundir",
  "Rajput - Raghu vanshi",
  "Rajput - Rajawal",
  "Rajput - Rajput Swarnkar",
  "Rajput - Rana",
  "Rajput - Rao",
  "Rajput - Rathore",
  "Rajput - Rawa Rajput",
  "Rajput - Rawal",
  "Rajput - Rohilla",
  "Rajput - Sagar Rajput",
  "Rajput - Sainthwar Rajput",
  "Rajput - Sarangdevot",
  "Rajput - Shakya",
  "Rajput - Shekhawat",
  "Rajput - Sikarwar",
  "Rajput - Singh",
  "Rajput - Sisodia",
  "Rajput - Solanki",
  "Rajput - Somvansha",
  "Rajput - Surwar",
  "Rajput - Suryavanshi",
  "Rajput - Tanwar",
  "Rajput - Thakur",
  "Rajput - Tomar",
  "Rajput - Ujjain",
  "Rajput - Vaishya",
  "Rajput Garhwali",
  "Rajput Kumaoni",
  "Ramdasia",
  "Ramgarhia",
  "Ramoshi Berad Bedar",
  "Ravidassia",
  "Rawat",
  "Reddy",
  "Reddy - Ayodhi",
  "Reddy - Bhoomanchi Reddy",
  "Reddy - Chowdary",
  "Reddy - Desuru",
  "Reddy - Gandla",
  "Reddy - Ganjam",
  "Reddy - Gone Kapu",
  "Reddy - Gudati",
  "Reddy - Kapu",
  "Reddy - Motati",
  "Reddy - Palle",
  "Reddy - Palnati",
  "Reddy - Panta",
  "Reddy - Pedakanti",
  "Reddy - Poknati",
  "Reddy - Reddiar",
  "Reddy - Sajjana",
  "Reddy - Vanni",
  "Reddy - Velanati",
  "Relli",
  "Rohit Chamar",
  "Ror",
  "Sadgope",
  "Saha",
  "Sahu",
  "Saini",
  "Saliya",
  "Samagar",
  "Sambava",
  "Santhali",
  "Sargara",
  "Sathwara",
  "Satnami",
  "Savji",
  "Sawantwadi",
  "Scheduled Caste",
  "Senai Thalaivar",
  "Senguntha Mudaliyar",
  "Settibalija",
  "Shah",
  "Shilpkar",
  "Shimpi",
  "Silawat",
  "Sillekyathala",
  "Sindhi",
  "Sindhi - Sindhi Amil",
  "Sindhi - Sindhi Baibhand",
  "Sindhi - Sindhi Bhanusali",
  "Sindhi - Sindhi Bhatia",
  "Sindhi - Sindhi Chhapru",
  "Sindhi - Sindhi Daru",
  "Sindhi - Sindhi Hyderabadi",
  "Sindhi - Sindhi Larai",
  "Sindhi - Sindhi Larkan",
  "Sindhi - Sindhi Larkana",
  "Sindhi - Sindhi Lohana",
  "Sindhi - Sindhi Rohiri",
  "Sindhi - Sindhi Sahiti",
  "Sindhi - Sindhi Sakkhar",
  "Sindhi - Sindhi Sehwan",
  "Sindhi - Sindhi Shikarpuri",
  "Sindhi - Sindhi Thatai",
  "Siyal",
  "SKP",
  "Somvanshi",
  "Somvanshi Kayastha Prabhu",
  "Sonkar",
  "Sonkar / Sunar",
  "Sourashtra",
  "Sozhiya Vellalar",
  "Srisayani",
  "SSK",
  "Subarna Banik",
  "Sudi Suri Sundhi Shaundik",
  "Sugali (Naika)",
  "Sutar",
  "Swakula Sali",
  "Swarnkar",
  "Tamboli",
  "Tammalali",
  "Tanti",
  "Tantuvay",
  "Telaga",
  "Teli",
  "Thachar / Thacharkulathor",
  "Thakkar",
  "Thandan",
  "Tharakan",
  "Thevar Mukkulathor",
  "Thevar Mukkulathor - Agamudayar",
  "Thevar Mukkulathor - Ambalakrar",
  "Thevar Mukkulathor - Appanad Kondaiyankottai Maravar",
  "Thevar Mukkulathor - Easanattu Kallar",
  "Thevar Mukkulathor - Kallar",
  "Thevar Mukkulathor - Maniyakarar",
  "Thevar Mukkulathor - Maravar",
  "Thevar Mukkulathor - Piramalai Kallar",
  "Thevar Mukkulathor - Rajakula Agamudayar",
  "Thevar Mukkulathor - Semmanad Maravar",
  "Thevar Mukkulathor - Servai",
  "Thevar Mukkulathor - Thanjavur Kallar",
  "Thevar Mukkulathor - Vallambar",
  "Thigala",
  "Thiyya",
  "Thiyya - Ezhava",
  "Thiyya - Kavuthiya",
  "Thiyya - Thiyya Thandan",
  "Tili",
  "Togata",
  "Tonk Kshatriya",
  "Turi",
  "Turupu Kapu",
  "Uppara",
  "Vadar",
  "Vaddera",
  "Vaduka",
  "Vaidiki Velanadu",
  "Vaish",
  "Vaish - Vaish Dhaneshawat",
  "Vaishnav",
  "Vaishnav - Bairagi Swami",
  "Vaishnav - Vaishnav Bhatia",
  "Vaishnav - Vaishnav Dishaval",
  "Vaishnav - Vaishnav Kapol",
  "Vaishnav - Vaishnav Khadyata",
  "Vaishnav - Vaishnav Lad",
  "Vaishnav - Vaishnav Modh",
  "Vaishnav - Vaishnav Porvad",
  "Vaishnav - Vaishnav Shrimalli",
  "Vaishnav - Vaishnav Sorathaiya",
  "Vaishnav - Vaishnav Vania",
  "Vaishnav Vanik",
  "Vaishnava - Brahmin Sri Vaishnava",
  "Vaishnava - Chhatada Sri Vaishnava",
  "Vaishnava - Sri Vaishnava",
  "Vaishya",
  "Vaishya - Mahuri",
  "Vaishya - Mathur Vaishya",
  "Vaishya Vani",
  "Vallala",
  "Valluvar",
  "Valmiki",
  "Valuvan",
  "Vania",
  "Vaniya",
  "Vaniya - Nair-Vaniya",
  "Vaniya - Vaniya Chettiar",
  "Vanjara",
  "Vanjari",
  "Vannar",
  "Vanniakula Kshatriyar",
  "Vanniakula Kshatriyar - Arasu",
  "Vanniakula Kshatriyar - Gounder",
  "Vanniakula Kshatriyar - Naicker",
  "Vanniakula Kshatriyar - Padayachi",
  "Vanniakula Kshatriyar - Palli",
  "Vanniakula Kshatriyar - Pandal",
  "Vanniakula Kshatriyar - Urs",
  "Vanniakula Kshatriyar - Vannia Reddiar",
  "Vanniakula Kshatriyar - Vanniyar",
  "Vanniyar",
  "Variar",
  "Varshney",
  "Veershaiva Veera Saivam",
  "Velaan",
  "Velama",
  "Velama - Adivelama",
  "Velama - Koppula",
  "Velama - Padmanayaka",
  "Velama - Polinati",
  "Velama - Yellapa",
  "Velan",
  "Vellalar",
  "Vellalar - Aaruv Nattu Vellala",
  "Vellalar - Agamudayar / Arcot / Thuluva Vellala",
  "Vellalar - Cherakula Vellalar",
  "Vellalar - Desikar",
  "Vellalar - Devendra Kula Vellalar",
  "Vellalar - Illaththu Pillai",
  "Vellalar - Isai Vellalar",
  "Vellalar - Karkathar",
  "Vellalar - Kodikal Pillai",
  "Vellalar - Kongu Vellala Gounder",
  "Vellalar - Nanjil Mudali",
  "Vellalar - Nanjil Nattu Vellalar",
  "Vellalar - Nanjil Vellalar",
  "Vellalar - Nankudi Vellalar",
  "Vellalar - Othuvaar",
  "Vellalar - Pandiya Vellalar",
  "Vellalar - Saiva Pillai Thanjavur",
  "Vellalar - Saiva Pillai Tirunelveli",
  "Vellalar - Saiva Vellalar",
  "Vellalar - Sengunthar / Kaikolar",
  "Vellalar - Sozhiya Vellalar",
  "Vellalar - Thondai Mandala Vellala",
  "Vellalar - Veerakodi",
  "Vellalar - Vellalar All",
  "Vettuva Gounder",
  "Vettuvan",
  "Vishwakarma",
  "Vishwakarma - Black Smith",
  "Vishwakarma - Carpentry (Vadrangi, Vadla)",
  "Vishwakarma - Goldsmiths",
  "Vishwakarma - Sculptor (Shilpi)",
  "Vokkaliga",
  "Vysya",
  "Wani",
  "Yadav / Yadava",
  "Yadav / Yadava - Aheer / Ahir",
  "Yadav / Yadava - Ala Golla",
  "Yadav / Yadava - Daddi",
  "Yadav / Yadava - Das",
  "Yadav / Yadava - Dhador",
  "Yadav / Yadava - Erragola",
  "Yadav / Yadava - Gadri / Gadariya",
  "Yadav / Yadava - Gauda",
  "Yadav / Yadava - Gawli",
  "Yadav / Yadava - Goal / Gola / Golla",
  "Yadav / Yadava - Gop / Gopal / Gopala",
  "Yadav / Yadava - Goriya",
  "Yadav / Yadava - Gwala",
  "Yadav / Yadava - Gwalvanshi",
  "Yadav / Yadava - Jadav",
  "Yadav / Yadava - Kohar",
  "Yadav / Yadava - Konar",
  "Yadav / Yadava - Korna",
  "Yadav / Yadava - Krishnath",
  "Yadav / Yadava - Kurudas Gollas",
  "Yadav / Yadava - Kuruma",
  "Yadav / Yadava - Mandal",
  "Yadav / Yadava - Manjrauth",
  "Yadav / Yadava - Nandvanshi",
  "Yadav / Yadava - Pakanati",
  "Yadav / Yadava - Puja",
  "Yadav / Yadava - Raut",
  "Yadav / Yadava - Suryavanshi",
  "Yadav / Yadava - Thethwar",
  "Yadav / Yadava - Yadav Golla",
  "Yadav / Yadava - Yaduvanshi",
  "Yellapu",
  "Other",
]

export const GOTRAS = [
  "Aatreya", "Abhimanyu", "Abhonasa", "Achutanand", "Aditya", "Agasthya", "Agni",
  "Agnihotri", "Agniweshya", "Agrawal", "Ahlawat", "Ahluwalia", "Ahuja", "Ainakula",
  "Ainand", "Ainthuvana", "Ajmera", "Akshinthal", "Aladrishi", "Alambayan", "Alimman",
  "Anakula", "Anand", "Ananthakul", "Angiras", "Angirasa", "Anhal", "Anthuvan",
  "Anuradha", "Anusham", "Arisetla", "Arunolla", "Arutla", "Ashlesha", "Ashvini",
  "Asura", "Aswalayana", "Atri", "Atriya", "Audichya", "Aujla", "Aulakh", "Ayyavarala",
  "Baberwal", "Bachasya", "Badarayana", "Badgujar", "Badhan", "Badwal", "Bagrecha",
  "Bagri", "Bains", "Bala", "Beniwal", "Bharadwaj", "Bharadwajeya", "Bhargava",
  "Bhrigu", "Bilas", "Billava", "Bindal", "Bisa Agarwal", "Bisen", "Bodayanah",
  "Brahachara", "Brahmakula", "Brar", "Bruhadashw", "Brungi", "Chandravanshi",
  "Daalbhyah", "Dabad", "Dabas", "Dadhichi", "Dagar", "Dahiya", "Darbaria", "Darji",
  "Datatri", "Debari", "Desatla", "Deshwal", "Dev", "Deval", "Devalachar",
  "Devarajasa", "Devarathah", "Devavalkya", "Devgan", "Dixit", "Dravida", "Durvasash",
  "Elisetla", "Enaganti", "Enukula", "Eran", "Eruvakula", "Ezhuthachacha", "Ezhuva",
  "Garg", "Garga", "Gautam", "Haihayavanshi", "Harita", "Ikshvaku", "Ikshwakula",
  "Inakala", "Indoria", "Jaabilih", "Jabal", "JadaBharat", "Jadon", "Jagarwal",
  "Jaimini", "Jaiswal", "Jakhar", "Jalakala", "Jalaneela", "Jamadagni", "Jeevanthi",
  "Jilakara", "Jindal", "Joshi", "Kadagam", "Kadva", "Kainth", "Kalepala", "Kaloti",
  "Kalra", "Kalsi", "Kalyan", "Kamakayana", "Kamandalam", "Kanva", "Kapila", "Kashyap",
  "Kashyapi", "Kaundinya", "Kaushika", "Kiriyath", "Kirodiwal", "Kondal", "Koundinya",
  "Koushika", "Krishna", "Krishnarth", "Krishnaut", "Krupacharya", "Kukreja", "Kumar",
  "Kumbala", "Kumbam", "Kumbhar", "Kurmi", "Kurup", "Kuthsah", "Ladhar", "Lakhanpal",
  "Lal", "Lamba", "Lavanga", "Lavania", "Leva", "Lingaayat", "Lodha", "Lohana",
  "Lohar", "Lohitasa", "Lomasha", "Longia", "Lunawat", "Macharla", "Madhesiya",
  "Madhurishi", "Magarishi", "Mahar", "Maharishi", "Mahavishnu", "Makara", "Mandavya",
  "Meenam", "Mehta", "Mervana", "Mesham", "Midhunakul", "Miglani", "Miriyala",
  "Mithunam", "Mittal", "Mudgal", "Mukkuva", "Mulakula", "Nabilla", "Nadar", "Nagdev",
  "Nagendra", "Nageswar", "Nagpal", "Nagula", "Neelam", "Neem", "Nigam", "Nimavat",
  "Ninave", "Niranjan", "Nirmal", "Nirvan", "Nityundan", "Ojha", "Oswal", "Pachori",
  "Padadasila", "Pahwa", "Paidipala", "Palakaya", "Parashara", "Parashariya",
  "Perisetla", "Perumal", "Pillai", "Pillutla", "Pingala", "Piplansh", "Poonia",
  "Porwal", "Poulasthya", "Prajapati", "Puligolla", "Pundir", "Raghav", "Raghukula",
  "Raghuvansh", "Raghuvanshi", "Rai", "Rajawat", "Rajpal", "Ramanujam", "Recharla",
  "Renuka", "Rishi", "Sandilya", "Sehrawat", "Sengar", "Shakalya", "Sharadvan",
  "Shaunaka", "Shaunakayana", "Sidhu", "Singhal", "Singhvi", "Somavanshi",
  "Srivastava", "Subramanya", "Sukanchana", "Suklarushi", "Sundarah", "Sundarasa",
  "Suparnasa", "Surya", "Suryakula", "Suryavansh", "Talluri", "Tandon", "Tayal",
  "Tilawat", "Tiwari", "Tulasi", "Tuteja", "Udavat", "Ullutla", "Upadhyay",
  "Upamanyu", "Vaikhanasa", "Vashishtha", "Vatsayana", "Vatsya", "Velisetla",
  "Vellalar", "Velpula", "Vennakula", "Verma", "Vishnu", "Vishwamitra", "Vyas",
  "Yaduvanshi", "Yagyavalkya",
  "Other",
]

export const MOTHER_TONGUES = [
  "Acehnese",
  "Afar",
  "Afrikaans",
  "Ainu",
  "Aka",
  "Akan (Twi)",
  "Albanian",
  "American Sign Language (ASL)",
  "Amharic",
  "Angika",
  "Angika variants",
  "Antillean Creole",
  "Apache",
  "Arabic",
  "Aramaic",
  "Armenian",
  "Arunachali",
  "Assamese",
  "Assyrian",
  "Awadhi",
  "Aymara",
  "Aymara variants",
  "Azerbaijani",
  "Badaga",
  "Bagri Rajasthani",
  "Balinese",
  "Balti",
  "Baluchi",
  "Bambara",
  "Banjarese",
  "Basque",
  "Belarusian",
  "Bengali",
  "Berber (Tamazight)",
  "Bhojpuri",
  "Bhutia",
  "Bihari",
  "Bikol",
  "Bislama",
  "Blackfoot",
  "Bodo",
  "Bosnian",
  "Brahui",
  "Breton",
  "Brij",
  "British Sign Language (BSL)",
  "Buginese",
  "Bulgarian",
  "Burmese",
  "Burushaski",
  "Cantonese",
  "Cape Verdean Creole",
  "Catalan",
  "Cebuano",
  "Chattisgarhi",
  "Chavacano",
  "Chechen",
  "Cherokee",
  "Chichewa",
  "Chickasaw",
  "Chin",
  "Chinese (Mandarin)",
  "Chinese Sign Language (CSL)",
  "Chittagonian",
  "Choctaw",
  "Chuukese",
  "Circassian",
  "Coorgi",
  "Coptic",
  "Corsican",
  "Cree",
  "Creek",
  "Croatian",
  "Cypriot Greek",
  "Cypriot Turkish",
  "Czech",
  "Dagbani",
  "Dakota",
  "Danish",
  "Dari",
  "Dhundhari / Jaipuri",
  "Dimasa",
  "Divehi (Maldivian)",
  "Dogri",
  "Dutch",
  "Embera",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Ewe variants",
  "Faroese",
  "Farsi (Persian)",
  "Fijian",
  "Finnish",
  "French",
  "French Sign Language (LSF)",
  "Frisian",
  "Fula (Fulfulde)",
  "Fulani",
  "Ga",
  "Gaddhi",
  "Galician",
  "Gan",
  "Garhwali",
  "Garo",
  "Georgian",
  "German",
  "German Sign Language (DGS)",
  "Gikuyu",
  "Gilbertese",
  "Greek",
  "Guarani",
  "Gujarati",
  "Gujari / Gojari",
  "Gullah",
  "Gurung",
  "Haitian Creole",
  "Hakka",
  "Harauti",
  "Haryanvi",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hiligaynon",
  "Himachali / Pahari",
  "Hindi",
  "Hindko",
  "Hmong",
  "Hungarian",
  "I-Kiribati",
  "Icelandic",
  "Igbo",
  "Ilocano",
  "Indian Sign Language (ISL)",
  "Indonesian",
  "Ingush",
  "Interlingua",
  "International Sign",
  "Inuit",
  "Inuktitut",
  "Irish (Gaelic)",
  "Italian",
  "Jamaican Patois",
  "Japanese",
  "Japanese Sign Language (JSL)",
  "Javanese",
  "K'iche'",
  "Kabyle",
  "Kachin",
  "Kakbarak",
  "Kalenjin",
  "Kamba",
  "Kanauji",
  "Kannada",
  "Kapampangan",
  "Kaqchikel",
  "Karbi",
  "Karen",
  "Kashmiri",
  "Kazakh",
  "Kazakh variants",
  "Khandesi",
  "Khasi",
  "Khmer (Cambodian)",
  "Kikongo",
  "Kikuyu",
  "Kinnauri",
  "Kinyarwanda",
  "Kirundi",
  "Kokborok",
  "Konkani",
  "Korean",
  "Koshali",
  "Kosraean",
  "Krio",
  "Kumaoni",
  "Kurdish (Kurmanji)",
  "Kurdish (Sorani)",
  "Kutchi",
  "Kyrgyz",
  "Kyrgyz variants",
  "Ladakhi",
  "Ladino",
  "Lahauli",
  "Lakota",
  "Lambadi",
  "Lao",
  "Latvian",
  "Laz",
  "Lepcha",
  "Lingala",
  "Lithuanian",
  "Louisiana Creole",
  "Luba-Katanga",
  "Luganda",
  "Luhya",
  "Luo",
  "Luxembourgish",
  "Macedonian",
  "Madurese",
  "Magahi",
  "Maithili",
  "Maithili variants",
  "Malay",
  "Malayalam",
  "Maltese",
  "Maltese Arabic",
  "Malvi",
  "Mam",
  "Mandinka",
  "Manipuri",
  "Maori",
  "Mapudungun (Mapuche)",
  "Marathi",
  "Marshallese",
  "Marwari",
  "Mauritian Creole",
  "Maya Yucatec",
  "Mayan",
  "Mende",
  "Meru",
  "Mewari",
  "Mewati / Ahirwati",
  "Miji",
  "Min Nan",
  "Minangkabau",
  "Mixtec",
  "Mizo",
  "Mon",
  "Mongolian",
  "Monpa",
  "Montenegrin",
  "Mossi (Moré)",
  "Nahuatl",
  "Navajo",
  "Ndebele",
  "Nepali",
  "Newari",
  "Nicobarese",
  "Nimadi",
  "Northern Sotho",
  "Norwegian",
  "Occitan",
  "Odia (Oriya)",
  "Ojibwe",
  "Okinawan",
  "Oromo",
  "Ossetian",
  "Otomi",
  "Paez",
  "Palauan",
  "Pangasinan",
  "Papiamento",
  "Pashto",
  "Persian",
  "Pohnpeian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Q'eqchi'",
  "Quechua",
  "Rajasthani",
  "Rakhine",
  "Reunionese Creole",
  "Rohingya",
  "Romanian",
  "Romansh",
  "Russian",
  "Ryukyuan",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Santhali",
  "Sardinian",
  "Scots Gaelic",
  "Seminole",
  "Seraiki",
  "Serbian",
  "Sesotho",
  "Setswana",
  "Seychellois Creole",
  "Shan",
  "Shekhawati",
  "Sherpa",
  "Shina",
  "Shona",
  "Sidamo",
  "Sikkimese (Bhutia variants)",
  "Sindhi",
  "Sinhalese (Sinhala)",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sourashtra",
  "Spanish",
  "Spiti",
  "Sundanese",
  "Swahili",
  "Swati (Swazi)",
  "Swedish",
  "Sylheti",
  "Tagalog (Filipino)",
  "Tahitian",
  "Taiwanese (Hokkien)",
  "Tajik",
  "Tamang",
  "Tamil",
  "Tatar",
  "Telugu",
  "Temne",
  "Thai",
  "Tharu",
  "Tibetan",
  "Tigre",
  "Tigrinya",
  "Tok Pisin",
  "Tongan",
  "Toto",
  "Tripuri",
  "Tshiluba",
  "Tsonga",
  "Tulu",
  "Turkish",
  "Turkmen",
  "Tuvaluan",
  "Twi-Fante",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Wagdi",
  "Waray",
  "Wayuu",
  "Welsh",
  "Wolaytta",
  "Wolof",
  "Wu (Shanghainese)",
  "Xhosa",
  "Xiang",
  "Yapese",
  "Yoruba",
  "Zapotec",
  "Zaza",
  "Zulu",
  "Other",
]


export const EDUCATIONS = [
  'Class 10th',
  'Class 12th',
  'Graduation',
  'Post Graduation',
  'Professional Degree',
  'Doctorate',
]

// "Degree" — specific qualification (B.Tech, MBBS, LLB, Ph.D, etc.),
// distinct from the coarse EDUCATIONS dropdown above. Grouped object so
// CreateProfile.js/Dashboard.js can render it as <optgroup> sections,
// with a search box on top filtering across all groups.
export const DEGREE_OPTIONS = {
  'Engineering': ['B.E / B.Tech', 'M.E / M.Tech', 'M.S Engineering',
    'B.Eng (Hons)', 'M.Eng (Hons)', 'Engineering Diploma', 'AE', 'AET',
    'A.M.E.', 'B.Plan', 'M.Plan', 'B.Tech LL.B.'],

  'Medicine & Healthcare': ['MBBS', 'BDS', 'BPT', 'BAMS', 'BHMS',
    'B.Pharma', 'BVSc', 'BSN / BScN', 'MDS', 'MCh', 'M.D.',
    'M.S Medicine', 'MPT', 'DM', 'M.Pharma', 'MVSc', 'MMed',
    'PGD Medicine', 'ADN', 'ANM', 'B.O.Th', 'B.P.E.S', 'B.P.Ed',
    'BCVT', 'BMLT', 'BMRIT', 'BMRT', 'BNYS', 'BOPTM', 'BOT', 'BPH',
    'BPMT', 'BPO', 'BRDIT', 'BUMS', 'D.P.Ed', 'D.Pharm', 'DMLT',
    'GNM', 'M.Optom.', 'MPH'],

  'Law': ['BL / LLB', 'ML / LLM', 'LLB (Hons)', 'ALA', 'B.A. LL.B.',
    'B.A. LL.B. (Hons)', 'B.Com LL.B.', 'B.L.S. LL.B.', 'BBA LL.B.',
    'BBA LL.B. (Hons)', 'M.B.L.', 'LL.D.'],

  'Doctorate': ['Ph.D', 'M.Phil', 'D.Litt', 'LL.D.', 'Pharm.D', 'Doctorate'],

  'Science': ['B.Sc', 'M.Sc', 'BSc (Hons)', 'DipSc', 'AS', 'AAS',
    'B.Agri.', 'B.Sc. (Post Basic)', 'B.Voc', 'M.Voc'],

  'Computer / IT': ['BCA', 'B.IT', 'BCS', 'BA Computer Science',
    'MCA', 'PGDCA', 'IT Diploma', 'ADIT', 'ADCA', 'DCA', 'MCM'],

  'Management': ['BBA', 'BHM', 'BBM', 'MBA', 'PGDM', 'ABA', 'ADBus',
    'B.H.A.', 'BAM', 'BFM', 'BFT', 'BHMCT', 'BHMTT', 'BMS', 'CWM',
    'Executive MBA', 'FPM', 'MAM', 'MBM', 'MHA', 'MHRM', 'MIB',
    'MMM', 'MMS', 'MTA', 'MTM'],

  'Finance / Commerce': ['B.Com', 'CA / CPA', 'CFA', 'CS',
    'BSc / BFin', 'M.Com', 'MSc / MFin / MS', 'BCom (Hons)',
    'PGD Finance', 'BBE', 'BBI', 'CFP', 'CIA', 'ICWA', 'MBE',
    'MBF', 'MFC', 'MFM'],

  'Arts / Design / Humanities': ['B.A', 'B.Ed', 'BJMC', 'BFA',
    'B.Arch', 'B.Des', 'BMM', 'MFA', 'M.Ed', 'M.A', 'MSW', 'MJMC',
    'M.Arch', 'M.Des', 'BA (Hons)', 'B.Arch (Hons)', 'DFA', 'D.Ed',
    'D.Arch', 'AA', 'AFA', 'B.El.Ed', 'B.F.Sc.', 'B.FAD', 'B.FTech',
    'B.J.', 'B.Lib.I.Sc.', 'B.Lib.Sc.', 'B.Litt', 'B.M.C.',
    'B.M.M.M.C.', 'B.Mus.', 'BCT & CA', 'BID', 'BPA', 'BSW', 'BVA',
    'D.El.Ed', 'D.Voc', 'ETT', 'M.F.Sc.', 'M.FTech', 'M.H.Sc.',
    'M.Lib.I.Sc.', 'M.Lib.Sc.', 'M.M.C.', 'M.O.L.', 'M.P.Ed', 'MID',
    'MPA', 'MVA', 'P.P.T.T.C', 'TTC'],

  'General': ['Bachelor', 'Master', 'Diploma', 'Honours', 'Associate'],

  'Non-Graduate': ['High School', 'Less than High School', 'Trade School'],

  'System': ['Others / Not in list', "Don't wish to specify"],
}

export const INCOME_RANGES = [
  'Below ₹2L/year', '₹2–5L', '₹5–10L', '₹10–20L', '₹20–35L', '₹35–50L',
  '₹50L–₹1Cr', '₹1Cr+', 'Prefer not to specify',
]

// ===================== ASSETS — Property / Vehicle / Business =====================
// Simplified structured fields replacing the old free-text "Property
// Details"/"Vehicle Details" inputs. Old property_details/vehicle_details
// columns are kept (backward compat) but no longer written to by the UI.

export const PROPERTY_TYPES = [
  'Independent House / Detached House', 'Villa', 'Bungalow', 'Duplex House',
  'Triplex House', 'Townhouse / Row House', 'Semi-Detached House',
  'Terraced House', 'Apartment / Flat', 'Condominium / Condo',
  'Studio Apartment', 'Penthouse', 'Builder Floor / Independent Floor',
  'Farmhouse', 'Cottage', 'Ancestral / Heritage House',
  'Village / Rural House', 'Haveli / Mansion', 'Mobile / Manufactured Home',
  'Other Residential Property', 'None', 'Prefer not to specify',
]

export const PROPERTY_OWNERSHIP = ['Self Owned', 'Family Owned', 'Jointly Owned', 'Rented', 'Other', 'Prefer not to specify']

export const VEHICLE_OWNERSHIP = [
  'No Vehicle', 'Two-Wheeler', 'Car', 'Car + Two-Wheeler',
  'Multiple Vehicles', 'Commercial Vehicle', 'Prefer not to specify',
]

// Partner Preference — Community multi-select. Appended to whichever
// religion-specific community list applies (same source used for the
// user's own Community field) after stripping that list's own generic
// "Other(s)"/"Don't wish to specify" entries, so there's one clean set
// of special options regardless of religion.
export const PARTNER_COMMUNITY_SPECIAL_OPTIONS = [
  'Inter-community', 'Any Community / No Bar', 'Others', "Don't wish to specify",
]
export const PARTNER_COMMUNITY_NO_BAR = 'Any Community / No Bar'

export const BUSINESS_ASSET_TYPES = [
  'Own Business', 'Family Business', 'Shop', 'Commercial Property',
  'Agricultural Land', 'Other', 'None', 'Prefer not to specify',
]

export const DIETS = ['Vegetarian', 'Non-Vegetarian', 'Occasionally Non-Vegetarian', 'Eggetarian', 'Jain', 'Vegan']

export const HABITS = ['Never', 'Occasionally', 'Yes']

export const FAMILY_TYPES = ['Nuclear', 'Joint', 'Extended']

export const FAMILY_VALUES = ['Orthodox', 'Conservative', 'Moderate', 'Liberal']

export const HEIGHT_RANGES = [
  '4\'0" (122 cm)',
  '4\'1" (124 cm)',
  '4\'2" (127 cm)',
  '4\'3" (130 cm)',
  '4\'4" (132 cm)',
  '4\'5" (135 cm)',
  '4\'6" (137 cm)',
  '4\'7" (140 cm)',
  '4\'8" (142 cm)',
  '4\'9" (145 cm)',
  '4\'10" (147 cm)',
  '4\'11" (150 cm)',
  '5\'0" (152 cm)',
  '5\'1" (155 cm)',
  '5\'2" (157 cm)',
  '5\'3" (160 cm)',
  '5\'4" (163 cm)',
  '5\'5" (165 cm)',
  '5\'6" (168 cm)',
  '5\'7" (170 cm)',
  '5\'8" (173 cm)',
  '5\'9" (175 cm)',
  '5\'10" (178 cm)',
  '5\'11" (180 cm)',
  '6\'0" (183 cm)',
  '6\'1" (185 cm)',
  '6\'2" (188 cm)',
  '6\'3" (191 cm)',
  '6\'4" (193 cm)',
  '6\'5" (196 cm)',
  '6\'6" (198 cm)',
  '6\'7" (201 cm)',
  '6\'8" (203 cm)',
  '6\'9" (206 cm)',
  '6\'10" (208 cm)',
  '6\'11" (211 cm)',
  '7\'0" (213 cm)',
  'Prefer not to specify',
]

export const MARITAL_STATUSES = ['Never Married', 'Divorced', 'Widowed', 'Separated', 'Awaiting Divorce', 'Annulled']

export const LOCATION_PREFERENCES = [
  'Same city',
  'Same state',
  'Anywhere in India',
  'Open to relocation',
  'Global',
]

// ===================== PHASE 1 EXPANSION — naye fields ke liye =====================

export const COMPLEXIONS = ['Very Fair', 'Fair', 'Wheatish', 'Wheatish Brown', 'Dark', 'Very Dark', 'Prefer not to specify']

export const BODY_TYPES = ['Slim', 'Athletic', 'Average', 'Heavy', 'Curvy', 'Prefer not to specify']

export const WEIGHT_RANGES = ['Below 45kg', '45–55kg', '55–65kg', '65–75kg', '75–85kg', 'Above 85kg']

export const NATIONALITIES = ['Indian', 'NRI - USA', 'NRI - UK', 'NRI - Canada', 'NRI - Australia', 'NRI - UAE/Gulf', 'NRI - Other', 'Other']

export const MANGLIK_OPTIONS = ['Manglik', 'Non-Manglik', "Don't Know"]

export const KUNDLI_AVAILABLE = ['Yes', 'No', 'Will arrange if needed']

export const RELOCATION_PREFERENCES = ['Not willing to relocate', 'Open to relocation within India', 'Open to relocation abroad', 'Flexible']

export const EMPLOYMENT_TYPES = ['Government', 'Private Sector', 'Business / Self-Employed', 'Not Working', 'Student', 'Retired']

export const INDUSTRIES = [
  'IT / Software', 'Banking / Finance', 'Healthcare / Medical', 'Education', 'Government / Public Sector',
  'Engineering / Manufacturing', 'Legal', 'Retail / Business', 'Media / Entertainment', 'Hospitality',
  'Agriculture', 'Real Estate', 'Defence / Armed Forces', 'Other',
]

export const OWN_HOUSE_OPTIONS = ['Own House', 'Rented', 'Family House']

export const HOUSE_TYPES = ['Independent House', 'Apartment/Flat', 'Farmhouse', 'Other']

export const FAMILY_INCOME_RANGES = ['Below ₹5L', '₹5–10L', '₹10–20L', '₹20–50L', '₹50L+']

export const PHYSICAL_DISABILITY_OPTIONS = ['No', 'Yes']

// ===================== PHASE 7 — Shaadi.com/Jeevansathi research se =====================

export const PROFESSION_CATEGORIES = [
  'Accounting, Banking & Finance', 'Administration & HR', 'Advertising, Media & Entertainment',
  'Agriculture', 'Airline & Aviation', 'Architecture & Design', 'Artists, Animators & Web Designers',
  'Beauty, Fashion & Jewellery Designers', 'BPO, KPO & Customer Support', 'Civil Services / Law Enforcement',
  'Corporate Professionals', 'Defense', 'Education & Training', 'Engineering', 'Hotel & Hospitality',
  'IT & Software Engineering', 'Legal', 'Medical & Healthcare', 'Merchant Navy', 'Not Working',
  'Sales & Marketing', 'Science', 'Others',
]

export const WORKING_WITH_OPTIONS = ['Private Company', 'Government / Public Sector', 'Defense / Civil Services', 'Business / Self Employed', 'Not Working']

export const HEALTH_INFO_OPTIONS = ['No Health Problems', 'HIV Positive', 'Diabetes', 'Low BP', 'High BP', 'Heart Ailments', 'Other']

export const BLOOD_GROUPS = ["Don't Know", 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']

export const PROFILE_MANAGED_BY = ['Self', 'Parent / Guardian', 'Sibling', 'Relative', 'Other']

export const FAMILY_STATUS_OPTIONS = ['Rich / Affluent', 'Upper Middle Class', 'Middle Class']

export const LIVING_WITH_PARENTS_OPTIONS = ['Yes', 'No', 'Not Applicable']

export const HOBBIES_INTERESTS = {
  Creative: ['Collecting Stamps', 'Collecting Coins', 'Collecting Antiques', 'Art / Handicraft', 'Painting', 'Cooking', 'Photography', 'Film-making', 'Model Building', 'Gardening / Landscaping', 'Playing Musical Instruments', 'Singing', 'Dancing', 'Acting', 'Writing', 'Blogging'],
  'Reading & Learning': ['Reading / Book Clubs', 'Learning New Languages', 'Solving Crosswords / Puzzles', 'Astrology / Palmistry / Numerology', 'Graphology'],
  Entertainment: ['Listening to Music', 'Movies', 'Theatre', 'Watching Television', 'Video / Computer Games', 'Ham Radio'],
  'Sports & Outdoor': ['Sports - Outdoor', 'Sports - Indoor', 'Trekking / Adventure Sports', 'Fishing', 'Bird Watching', 'Travel / Sightseeing'],
  'Wellness & Social': ['Health & Fitness', 'Yoga / Meditation', 'Alternative Healing', 'Taking Care of Pets', 'Volunteering / Social Service', 'Politics', 'Net Surfing'],
}
export const HOBBIES_MAX_SELECT = 5

export const FAVOURITE_MUSIC = [
  'Classical - Hindustani', 'Classical - Carnatic', 'Classical - Western', 'Instrumental - Indian',
  'Instrumental - Western', 'Old Film Songs', 'Latest Film Songs', 'Ghazals', 'Qawalis',
  'Bhajans / Devotional', 'Sufi Music', 'Indipop', 'Pop', 'Disco', 'House Music', 'Techno',
  'Hip-Hop', 'Rap', 'Jazz', 'Blues', 'Reggae', 'Heavy Metal', 'Acid Rock',
]

export const FAVOURITE_BOOKS = [
  'Classic Literature', 'Biographies', 'History', 'Poetry', 'Romance', 'Thriller / Suspense',
  'Humour', 'Science Fiction', 'Fantasy', 'Business / Occupational', 'Philosophy / Spiritual',
  'Self-help', 'Short Stories', 'Comics', 'Magazines & Newspapers',
]

export const DRESS_STYLES = [
  'Classic Indian', 'Trendy', 'Classic Western', 'Designer', 'Casual',
]

export const CUISINES = [
  'North Indian', 'South Indian', 'Punjabi', 'Gujarati', 'Rajasthani', 'Bengali', 'Konkani',
  'Chinese', 'Continental', 'Mughlai', 'Italian', 'Arabic', 'Thai', 'Sushi', 'Mexican',
  'Lebanese', 'Latin American', 'Spanish', 'Fast Food',
]

export const SPORTS_LIST = [
  'Cricket', 'Football', 'Basketball', 'Tennis', 'Badminton', 'Swimming / Water Sports',
  'Jogging / Walking', 'Cycling', 'Yoga / Meditation', 'Gym / Weight Training', 'Chess',
  'Carrom', 'Card Games', 'Table Tennis', 'Adventure Sports',
]

// Fine-grained height dropdown, feet+inches WITH cm — Shaadi.com jaisa
export function generateHeightOptions() {
  const options = []
  for (let totalInches = 53; totalInches <= 84; totalInches++) { // 4'5" to 7'0"
    const feet = Math.floor(totalInches / 12)
    const inches = totalInches % 12
    const cm = Math.round(totalInches * 2.54)
    options.push(`${feet}ft ${inches}in — ${cm}cm`)
  }
  return options
}
export const HEIGHT_OPTIONS_DETAILED = generateHeightOptions()

// NOTE: "Not Filled" ≠ "No" — koi bhi field jo user ne bhari nahi hai,
// khaali/blank hi rehni chahiye database mein (kabhi bhi false/No
// auto-set nahi karna). Poore CreateProfile.js/EditProfileForm mein
// yeh already follow ho raha hai — sab dropdowns ka default
// <option value="">Select</option> hai, "No" nahi.

// ===================== PHASE 9 — Jeevansathi/Shaadi.com deeper research =====================

export const TIME_OF_BIRTH_ACCURACY = ['I know my exact time of birth', 'I know my approximate time of birth', "Don't know"]

export const CASTE_NO_BAR_OPTIONS = ['Yes', 'No']

// "Privacy level" — kis field ko kaun dekh sakta hai (Company/College/
// Income/Contact ke liye same 5 levels use hote hain)
// 3-tier privacy model (simplified from the earlier 5-level system):
// Public = visible to anyone browsing; Matches Only = visible only to
// profiles that have crossed the mutual-interest/match threshold;
// Private = never shown to other users, visible only to staff (staff
// always see full profile data regardless of this value — see
// "staff can view all profiles" RLS policy on profiles, which has no
// privacy-based qual).
export const PRIVACY_LEVELS = ['Public', 'Matches Only', 'Private']

// ===================== ISLAM — Denomination / Sect / Community =====================
// Sirf religion === 'Muslim' hone par CreateProfile.js/Dashboard.js mein
// yeh cascading flow dikhta hai: Denomination -> School of Thought (Sunni)
// ya Shia Branch (Shia) -> Community (ISLAMIC_COMMUNITIES, CASTES ki jagah).

export const ISLAMIC_DENOMINATIONS = [
  'Sunni',
  'Shia',
  'Ibadi',
  'Ahmadiyya',
  'Other denomination',
  'Just Muslim (no specific denomination)',
  'Prefer not to specify',
]

export const SUNNI_SCHOOLS_OF_THOUGHT = [
  'Hanafi',
  'Shafi',
  'Maliki',
  'Hanbali',
  'Not specific to any school',
  'Prefer not to specify',
]

export const SHIA_BRANCHES = [
  'Ithna Ashari (Twelver)',
  'Ismaili',
  'Zaydi',
  'Other Shia branch',
  'Prefer not to specify',
]

// Islam-specific "Community/Caste" dropdown, replaces CASTES when
// religion === 'Muslim'. "Other" free-text fallback already handled by
// the existing community_other pattern. Cross-checked against
// BharatMatrimony's production list (July 2026): ONE shared list is used
// for both Sunni and Shia (not duplicated per-sect) — the UI never
// branches this list by denomination, only Step 2's Denomination select
// itself does.
export const ISLAMIC_COMMUNITIES = [
  // India-specific matrimonial-standard castes
  'Ansari', 'Arain', 'Awan', 'Barhai', 'Chikwa', 'Dekkani', 'Dhunia',
  'Dudekula', 'Hajjam', 'Hanafi', 'Jat', 'Kabaria', 'Khoja', 'Kumhar',
  'Lebbai', 'Malik', 'Manihar', 'Mapila', 'Maraicar', 'Memon', 'Mughal',
  'Pathan', 'Qureshi', 'Rajput', 'Rowther', 'Shafi', 'Sheikh',
  'Sheikh Syed', 'Siddiqui', 'Syed', 'Teli', 'Unspecified',
  // Bohra split into 3 distinct sub-groups
  'Alavi Bohra', 'Dawoodi Bohra', 'Sunni Bohra',
  // Broader regional/ethnic (global reach)
  'Arab', 'Turkish', 'Persian', 'Bengali Muslim', 'Punjabi Muslim',
  'Egyptian Arab', 'Indonesian', 'Pakistani', 'Malay', 'Kashmiri Muslim',
  'Afghan', 'Baloch', 'Sindhi Muslim', 'Javanese', 'Moroccan Arab',
  'Saudi', 'Iraqi Arab', 'Syrian Arab', 'Lebanese', 'Palestinian',
  'Somali', 'Nigerian Muslim', 'Sudanese Arab', 'Yemeni', 'Uzbek',
  'Kazakh', 'Tajik', 'Uyghur', 'Tatar', 'Bosniak', 'Albanian Muslim',
  'Chechen', 'Swahili', 'Hausa', 'Fulani', 'Rohingya', 'Kurdish',
  'African American Muslim', 'Gujarati Muslim',
  'Other',
]

// Optional third tier below Community — a more specific division within
// some communities (e.g. Sheikh -> Farooqui/Hashmi/Qazi). Not applicable
// to every community, so this stays optional with a neutral default.
export const ISLAMIC_SUB_CASTE_DIVISIONS = [
  'Dhobi', 'Farooqui', 'Gada', 'Gadri Ghosi', 'Gaddi', 'Ganchi', 'Gujar',
  'Hashmi', 'Iraqi Kalal', 'Kamboj', 'Khatri', 'Khotta', 'Konkani',
  'Kulhaiya', 'Laskar', 'Mansoori', 'Pinjara', 'Meitei Pangal', 'Meo',
  'Molla', 'Mondal', 'Munshi', 'Nagori', 'Nashya Sheikh', 'Nawayath',
  'Punjabi Shamsi', 'Qaimkhani', 'Qazi', 'Quadriya', 'Rahmani',
  'Rangrez', 'Sabaag', 'Rayeen', 'Saifi', 'Salmani', 'Sandhi', 'Sardar',
  'Sarkar', 'Shah Alvi', 'Shershabadia', 'Shikalgara', 'Soni', 'Soomro',
  'Sri Lankan', 'Talukdar', 'Tamboli', 'Thangal', 'Tyagi', 'Araki',
  'Abbasi', 'Assamese Muslim', 'Attar', 'Bagwan', 'Bangladeshi', 'Beary',
  'Bhat', 'Chhipa', 'Choudhary', 'Darzi', 'Idrisi Sheikh',
  'Not Applicable', 'Other',
]

// Communities jinke liye UI mein extra-privacy inline-note dikhana hai
// jab user inhe select kare (denomination-level sensitivity jaise
// Ahmadiyya Step-2 mein hi handle ho jaati hai — yeh sirf community-level).
export const SENSITIVE_COMMUNITIES = ['Alavi Bohra', 'Dawoodi Bohra', 'Sunni Bohra', 'Rohingya', 'Uyghur']
export const SENSITIVE_COMMUNITY_NOTE = 'Yeh community ke liye extra privacy options available hain — aap chahein to apni profile mein isse zyada control mein rakh sakte hain.'

// ===================== CHRISTIAN — Denomination / Community =====================
// Sirf religion === 'Christian' hone par CreateProfile.js/Dashboard.js mein
// Denomination dropdown (grouped by parent_group via <optgroup>) aur
// Community dropdown (CHRISTIAN_COMMUNITIES, CASTES/ISLAMIC_COMMUNITIES ki
// jagah) dikhta hai. Same lightweight flat-array pattern jaisa Hindu/Muslim
// ke liye already hai — koi master table/FK/RPC nahi.
export const CHRISTIAN_DENOMINATION_GROUPS = [
  {
    group: 'Catholic',
    options: [
      'Roman Catholic',
      'Syro-Malabar Catholic',
      'Syro-Malankara Catholic',
      'East Indian Catholic',
      'Catholic - Knanaya',
      'Catholic - Syrian',
    ],
  },
  {
    group: 'Orthodox / Syrian',
    options: [
      'Malankara Orthodox Syrian',
      'Jacobite',
      'Knanaya Jacobite',
      'Chaldean Syrian',
      'Syrian Orthodox',
    ],
  },
  {
    group: 'Mar Thoma',
    options: [
      'Mar Thoma',
      'St. Thomas Evangelical',
      'Malabar Independent Syrian Church',
    ],
  },
  {
    group: 'CSI / CNI',
    options: [
      'Church of South India',
      'Church of North India',
    ],
  },
  {
    group: 'Protestant',
    options: [
      'Protestant', 'Anglican', 'Baptist', 'Brethren', 'Born Again',
      'Calvinist', 'Congregational', 'Evangelical', 'Lutheran', 'Methodist',
      'Mennonite', 'Moravian', 'Presbyterian', 'Reformed Baptist',
      'Pentecostal', 'Apostolic', 'Adventist', 'Assembly of God',
      'Church of God', 'Church of Christ',
    ],
  },
  {
    group: 'Other',
    options: [
      "Jehovah's Witnesses",
      'Latter-day Saints',
      'Melkite',
      'Others',
      "Don't know denomination",
      "Don't wish to specify",
    ],
  },
]

export const CHRISTIAN_COMMUNITIES = [
  'Knanaya',
  'Anglo-Indian',
  'Nadar Christian',
  'Mangalorean Christian',
  'Dalit Christian',
  'Others',
  "Don't know community",
  "Don't wish to specify",
]

// ===================== OTHER RELIGIONS — Denomination/Tradition + Community =====================
// Same lightweight flat-array pattern as Hindu/Muslim/Christian above.
// RELIGION_HIERARCHY drives ONE generic, data-driven UI block (used for
// every religion below) instead of a hand-written block per religion —
// Muslim aur Christian apne existing hand-written cascading blocks pe
// hi rehte hain (unhe yahan touch nahi kiya), yeh sirf naye religions
// ke liye hai.

export const JAIN_SECTS = ['Shwetambar', 'Digambar', "Don't wish to specify"]

export const JAIN_COMMUNITIES = [
  'Agarwal', 'Asati', 'Ayodhyavasi', 'Bagherwal', 'Bania', 'Barhiya',
  'Charanagare', 'Chaturtha', 'Dhakada', 'Gahoi / Grihapati',
  'Golalare / Kharaua', 'Golapurva', 'Golsinghare', 'Harada',
  'Humad / Humbad', 'Jaiswal', 'Kambhoja', 'Kasar', 'Kathanere',
  'Khandelwal', 'Kutchi', 'KVO', 'Lamechu', 'Nema', 'Oswal',
  'Padmavati Porwal', 'Palliwal', 'Panchama', 'Parmar',
  'Parwar / Paravara', 'Porwal', 'Saitwal', 'Samanar / Nayinar',
  'Samiya', 'Sarak', 'Shrimal', 'Upadhyaya', 'Vaishya', 'Veerwal',
  'Intercaste', 'Others / Not in list', "Don't wish to specify",
]

// Jain-only gotra list — Hindu's existing GOTRAS (287 entries, shipped
// separately) is NOT touched or reused here.
export const JAIN_GOTRAS = [
  'Atri', 'Bharadwaj', 'Bhrigu', 'Chandravanshi', 'Gautam',
  'Garg', 'Jamadagni', 'Kaashyap / Kashyap', 'Katyayan',
  'Kaundinya', 'Krittika', 'Kulish', 'Kundal', 'Mandavya',
  'Maudgalya', 'Parashara', 'Shandilya', 'Shrivatsa',
  'Suryadhwaj', 'Upamanyu', 'Vashisht / Vashistha',
  'Vatsa', 'Vishwamitra',
  'Others / Not in list', "Don't wish to specify", 'Gotra not applicable',
]

export const SIKH_RELIGIOUS_IDENTITY = ['Gursikh', 'Kesadhari', "Don't wish to specify"]

export const SIKH_COMMUNITIES = [
  'Ahluwalia', 'Arora', 'Bhatia', 'Bhatra', 'Ghumar',
  'Jat - Achara', 'Jat - Bhakar', 'Jat - Dhatarwal', 'Jat - Janu',
  'Jat - Kuntal', 'Jat - Poria', 'Jat - Sheokhand', 'Jat - Tangar',
  'Kamboj', 'Kashyap Rajput',
  'Khatri - Batta', 'Khatri - Bindra', 'Khatri - Dhingara', 'Khatri - Mehra / Malhotra',
  'Labana / Lubana', 'Mazhabi', 'Nai', 'Prajapati', 'Rai Sikh',
  'Rajput - Kalyanot', 'Rajput - Karadiya / Nadoda', 'Rajput - Mair Rajput Swarnkar',
  'Rajput - Pathania', 'Rajput - Rawat', 'Rajput - Sengar', 'Rajput - Verma',
  'Ramdasia', 'Ramgarhia', 'Ravidasia', 'Saini', 'Tonk Kshatriya',
  'Intercaste', 'Others / Not in list', "Don't wish to specify",
]

export const BUDDHIST_TRADITIONS = [
  'Navayana / Ambedkarite Buddhist', 'Marathi Buddhist',
  'Tibetan / Himalayan Buddhist', 'Theravada Buddhist',
  'Mahayana Buddhist', 'Vajrayana Buddhist',
  'Other Buddhist Tradition', "Don't wish to specify",
]

export const BUDDHIST_COMMUNITIES = [
  'Mahar', 'Marathi Buddhist', 'Navnath',
  'Tibetan / Himalayan Community', 'Newar Buddhist',
  'Inter-community', 'Others / Not in list', "Don't wish to specify",
]

export const ZOROASTRIAN_COMMUNITY = [
  'Parsi', 'Irani Zoroastrian', 'Other Zoroastrian',
  'Inter-community', "Don't wish to specify",
]

export const ZOROASTRIAN_CALENDAR = [
  'Shahenshahi', 'Kadmi / Qadimi', 'Fasli', "Don't wish to specify",
]

export const JEWISH_DENOMINATIONS = [
  'Orthodox Judaism', 'Conservative Judaism', 'Reform Judaism',
  'Reconstructionist Judaism', 'Karaite Judaism', 'Jewish Renewal',
  'Secular / Cultural Jewish', 'Just Jewish / Non-denominational',
  "Don't wish to specify",
]

export const JEWISH_COMMUNITIES = [
  'Bene Israel', 'Cochin Jewish', 'Baghdadi Jewish', 'Bene Menashe',
  'Bene Ephraim', 'Paradesi Jewish', 'Ashkenazi Jewish', 'Sephardi Jewish',
  'Mizrahi Jewish', 'Yemenite Jewish', 'Bukharan Jewish', 'Georgian Jewish',
  'Ethiopian Jewish', 'Romaniote Jewish', 'Mountain Jewish',
  'Inter-community', 'Others / Not in list', "Don't wish to specify",
]

export const SHINTO_TRADITIONS = [
  'Shrine Shinto', 'Sect Shinto', 'Folk Shinto',
  'Shinto-Buddhist', 'Other Shinto Tradition', "Don't wish to specify",
]

export const SHINTO_COMMUNITIES = [
  'Japanese', 'Ryukyuan / Okinawan',
  'Others / Not in list', "Don't wish to specify",
]

export const TAOIST_TRADITIONS = [
  'Zhengyi / Orthodox Unity', 'Quanzhen / Complete Reality',
  'Shangqing', 'Lingbao', 'Folk / Popular Taoism',
  'Other Taoist Tradition', "Don't wish to specify",
]

export const TAOIST_COMMUNITIES = [
  'Chinese', 'Taiwanese', 'Southeast Asian Chinese',
  'Other Chinese Diaspora', 'Others / Not in list', "Don't wish to specify",
]

// Generic community-only religions — no denomination field, just this
// 2-option list (Others / Not in list, Don't wish to specify).
export const GENERIC_COMMUNITY_OPTIONS = ['Others / Not in list', "Don't wish to specify"]

const GENERIC_COMMUNITY_RELIGIONS = [
  "Baha'i", 'Confucianism', 'Druze', 'Yazidism', 'Rastafari', 'Tenrikyo',
  'Pagan', 'Unitarian Universalism', 'New Religious Movements',
  'Indigenous / Traditional', 'Samaritanism',
]

// "No Religion" group — hide Denomination + Community fields entirely.
export const NO_RELIGION_VALUES = [
  'Atheist', 'Agnostic', 'Spiritual but not Religious', 'Secular / Humanist', 'No Religion',
]

// Drives the generic, data-driven Denomination/Community UI block for
// every religion below (Hindu/Muslim/Christian keep their own existing
// hand-written blocks and are NOT in this lookup).
export const RELIGION_HIERARCHY = {
  Jain: {
    denomination: { label: 'Sect', options: JAIN_SECTS },
    community: { label: 'Community', options: JAIN_COMMUNITIES },
  },
  Sikh: {
    denomination: { label: 'Religious Identity', options: SIKH_RELIGIOUS_IDENTITY },
    community: { label: 'Community', options: SIKH_COMMUNITIES },
  },
  Buddhist: {
    denomination: { label: 'Tradition', options: BUDDHIST_TRADITIONS },
    community: { label: 'Community', options: BUDDHIST_COMMUNITIES },
  },
  Zoroastrian: {
    denomination: { label: 'Community', options: ZOROASTRIAN_COMMUNITY },
    community: { label: 'Religious Calendar', options: ZOROASTRIAN_CALENDAR },
  },
  Jewish: {
    denomination: { label: 'Denomination', options: JEWISH_DENOMINATIONS },
    community: { label: 'Community / Heritage', options: JEWISH_COMMUNITIES },
  },
  Shinto: {
    denomination: { label: 'Tradition', options: SHINTO_TRADITIONS },
    community: { label: 'Community', options: SHINTO_COMMUNITIES },
  },
  Taoist: {
    denomination: { label: 'Tradition', options: TAOIST_TRADITIONS },
    community: { label: 'Community', options: TAOIST_COMMUNITIES },
  },
  ...Object.fromEntries(GENERIC_COMMUNITY_RELIGIONS.map(r => [
    r,
    { community: { label: 'Community', options: GENERIC_COMMUNITY_OPTIONS } },
  ])),
}

// Family Financial Status — jaisa research mein exact categories mile
// (income-range ke saath), FAMILY_INCOME_RANGES se zyada precise hai
export const FAMILY_FINANCIAL_STATUS = [
  { label: 'Elite', desc: 'Large business or exceptional professional background', range: 'Above ₹70 Lakhs' },
  { label: 'High', desc: 'Mid-sized business or leadership positions', range: '₹30–70 Lakhs' },
  { label: 'Middle', desc: 'Small business or office jobs', range: '₹10–30 Lakhs' },
  { label: 'Aspiring', desc: 'Limited means, striving for better lifestyle', range: 'Up to ₹10 Lakhs' },
]

export const WORKING_AS_OPTIONS = [
  'Team Member / Staff', 'Team Lead / Supervisor', 'Manager', 'Senior Manager', 'Director / VP',
  'CXO / Founder', 'Business Owner', 'Consultant', 'Freelancer',
]
