-- matching.js ab Partner Country Preference aur Income Preference ko
-- real fields se compare karta hai (pehle dono ignore ho rahe the) —
-- iske liye profiles_public_view mein do columns chahiye jo pehle nahi
-- the: `country` (current residence — partner_country_preference isi se
-- compare hota hai, nationality se nahi) aur `annual_income_currency`
-- (annual_income ka slab string kis currency mein hai, taaki galat
-- currency cross-compare na ho).

create or replace view public.profiles_public_view as
 SELECT id,
    user_id,
    profile_code,
    mask_full_name(full_name) AS full_name,
    age,
    gender,
    city,
    state,
    religion,
    community,
    sub_caste,
    gotra,
    manglik,
    mother_tongue,
    education,
    diet,
    smoking,
    drinking,
    family_type,
    family_values,
    marital_status,
    height,
    weight,
    complexion,
    body_type,
    nationality,
    relocation_preference,
    annual_income,
    profile_completeness,
    profile_status,
    partner_age_min,
    partner_age_max,
    partner_religion,
    partner_location,
    partner_education,
    created_at,
    about_me,
    employer,
    college_name,
    father_profession,
    mother_profession,
    brothers_count,
    brothers_married_count,
    sisters_count,
    sisters_married_count,
    family_city,
    kundli_available,
    partner_height_min,
    partner_height_max,
    partner_income_min,
    partner_income_max,
    partner_income_currency,
    partner_community_ids,
    partner_education_level_preferences,
    partner_city_preference,
    partner_state_preference,
    partner_country_preference,
    partner_notes,
    profile_for,
    verification_status,
    country,
    annual_income_currency
   FROM profiles
  WHERE profile_status = 'active'::text AND (hidden_until IS NULL OR hidden_until < now());
